// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyrcjusumglfyqsluoam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cmNqdXN1bWdsZnlxc2x1b2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODE3NTAsImV4cCI6MjA2MzM1Nzc1MH0.Z7eupopyIVaTOX5lIlwRge5OVXKpYFqdHOHQcBNjibE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);